FORT = gfortran-12

OPTC = O2

MA48_LIB = 0

algen_dir = ../ALGEN
chole_dir = ../CHOLE
digis_dir = ../DIGIS
fftw3_dir = ../FFTW3
files_dir = ../FILES
gplot_dir = ../GPLOT
intpl_dir = ../INTPL
least_dir = ../LEAST
minim_dir = ../MINIM
msolv_dir = ../MSOLV
qsort_dir = ../QSORT
randm_dir = ../RANDM
splin_dir = ../SPLIN
tchev_dir = ../TCHEV
utils_dir = ../UTILS


