test_gnufor – TOOLIB
test_gnufor Program
John Burkardt
11 statements
Source File
Uses
gnufor
A fortran api to GNUPLOT. Example of use.
Calls
Source Code
program test_gnufor
use gnufor
implicit none
   call test01()
   call test02()
   call test03()
   call test04()
   call test05()
   call test06()
stop
endprogram test_gnufor
Call graph
test_gnufor calls test01, test02, test03, test04, test05, test06
test01 calls run_gnuplot, write_xy_data, write_xy_plot
test02 calls run_gnuplot, write_xyy_data, write_xyy_plots
test03 calls pi, run_gnuplot, write_xyz_data, write_xyz_plot
test04 calls run_gnuplot, write_vector_data, write_vector_plot
test05 calls run_gnuplot, write_xyzgrid_data, write_xyzgrid_surface
test06 calls run_gnuplot, write_xyzgrid_contour, write_xyzgrid_data
write_vector_data calls get_unit
write_vector_plot calls get_unit
write_xy_data calls get_unit
write_xy_plot calls get_unit
write_xyy_data calls get_unit
write_xyy_plots calls get_unit
write_xyz_data calls get_unit
write_xyz_plot calls get_unit
write_xyzgrid_contour calls get_unit
write_xyzgrid_data calls get_unit
write_xyzgrid_surface calls get_unit