abs_diff_sk_ku – TOOLIB
abs_diff_sk_ku Function
8 statements
Source File
function abs_diff_sk_ku(chrom)
Arguments
Type Intent Optional Attributes Name
real(kind=R8), intent(in), dimension(1:2) :: chrom
Return Value real(kind=r8)
Calls
Called by
Call graph
abs_diff_sk_ku calls sk_ku
sk_ku calls add_tang, tang
add_tang calls tang
cost calls abs_diff_sk_ku
cost_func calls abs_diff_sk_ku
newton_raphson_downhill calls abs_diff_sk_ku
test_algen calls abs_diff_sk_ku, newton_raphson_downhill