add_tang – TOOLIB
add_tang Function
10 statements
Source File
function add_tang(n, deb, fin, alp, bet, mu, si)
Arguments
Type Intent Optional Attributes Name
integer(kind=i4), intent(in) :: n
integer(kind=i4), intent(in) :: deb
integer(kind=i4), intent(in) :: fin
real(kind=R8), intent(in) :: alp
real(kind=R8), intent(in) :: bet
real(kind=R8), intent(in) :: mu
real(kind=R8), intent(in) :: si
Return Value real(kind=r8)
Calls
Called by
Call graph
add_tang calls tang
sk_ku calls add_tang
abs_diff_sk_ku calls sk_ku
cost calls abs_diff_sk_ku
cost_func calls abs_diff_sk_ku
newton_raphson_downhill calls abs_diff_sk_ku
test_algen calls abs_diff_sk_ku, newton_raphson_downhill