close_superlu – TOOLIB
close_superlu Subroutine
17 statements
Source File
public subroutine close_superlu(sulu)
Subroutine to close the SuperLU process, with memory release
Arguments
Type Intent Optional Attributes Name
type(SULU_ENV), intent(inout) :: sulu
Calls
Called by
Source Code
   subroutine close_superlu(sulu)
   !! Subroutine to close the SuperLU process, with memory release
   implicit none
   type(SULU_ENV), intent(inout) :: sulu
      call Destroy_CompCol_Matrix(sulu%SMA)
      call Destroy_Dense_Matrix(  sulu%smb)
      call Destroy_Dense_Matrix(  sulu%smx)
      deallocate( sulu%perm_c )
      deallocate( sulu%perm_r )
      deallocate( sulu%etree  )
      deallocate( sulu%RR )
      deallocate( sulu%CC )
      deallocate( sulu%ferr )
      deallocate( sulu%berr )
      deallocate( sulu%rpg   )
      deallocate( sulu%rcond )
   return
   endsubroutine close_superlu
Call graph
close_superlu calls destroy_compcol_matrix, destroy_dense_matrix
close_solver calls close_superlu
solve_syst calls close_solver, solution_solver
solution_solver calls solve_syst
test_solvers calls solve_syst