cost – TOOLIB
cost Subroutine
8 statements
Source File
subroutine cost(me, x, f)
Arguments
Type Intent Optional Attributes Name
class(pikaia_class), intent(inout) :: me
real(kind=R8), intent(in), dimension(:) :: x
real(kind=R8), intent(out) :: f
Calls
Source Code
   subroutine cost(me, x, f)
   implicit none
   class(pikaia_class), intent(inout)               :: me
   real(kind=R8)      , intent(in   ), dimension(:) :: x
   real(kind=R8)      , intent(  out)               :: f
      f = 1./(1. + abs_diff_sk_ku(chrom = x(1:2)))
   return
   endsubroutine cost
Call graph
cost calls abs_diff_sk_ku
abs_diff_sk_ku calls sk_ku
sk_ku calls add_tang, tang
add_tang calls tang