empty – TOOLIB
empty Subroutine
6 statements
Source File
public subroutine empty(charinout)
Just empties a string
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(inout) :: charinout
Called by
Source Code
   subroutine empty(charinout)
   !! Just empties a string
   implicit none
   character(len=*), intent(inout) :: charinout
      charinout = repeat(' ', len(charinout))
   return
   endsubroutine empty
Call graph
c_f_string calls empty
init_scal calls empty
trans_surf_txt calls empty, c_f_string
open_surffile calls trans_surf_txt, surf2scal
surf2scal calls c_f_string
test_surfile calls init_scal, trans_surf_txt, read_surf, write_surf
read_surf calls open_surffile
write_surf calls surf2scal