end_fftw3 – TOOLIB
end_fftw3 Subroutine
10 statements
Source File
public subroutine end_fftw3()
FFTW3 is no more useful from here. 1 FFT distributed on several threads
Arguments
None
Calls
Called by
Source Code
   subroutine end_fftw3()
   !! FFTW3 is no more useful from here. *1 FFT distributed on several threads*
   implicit none
      if ( SINGL_FFTW_ALLOCATED ) then
         call destroy_plan_fftw3()
         call desalloc_fftw3()
      endif
      SINGL_FFTW_ALLOCATED = .false.
      FFT_DIM(1:2) = [0, 0]
   return
   endsubroutine end_fftw3
Call graph
end_fftw3 calls desalloc_fftw3, destroy_plan_fftw3
desalloc_fftw3 calls fftw_free
destroy_plan_fftw3 calls fftw_destroy_plan
calc_fftw3 calls end_fftw3
calc_fftw3_real_bwd calls end_fftw3
calc_fftw3_real_fwd calls end_fftw3
test_fftw3 calls end_fftw3, calc_fftw3, calc_fftw3_real_bwd, calc_fftw3_real_fwd