enorm – TOOLIB
enorm Function
8 statements
Source File
public function enorm(n, x)
ENORM computes the Euclidean norm of a vector.
Arguments
Type Intent Optional Attributes Name
integer(kind=4) :: n
real(kind=8) :: x(n)
Return Value real(kind=8)
Called by
Source Code
function enorm(n, x)
!*****************************************************************************80
!
!! ENORM computes the Euclidean norm of a vector.
!
!  Discussion:
!
!    This is an extremely simplified version of the original ENORM
!    routine, which has been renamed to "ENORM2".
!
!  Licensing:
!
!    This code may freely be copied, modified, and used for any purpose.
!
!  Modified:
!
!    06 April 2010
!
!  Author:
!
!    Original FORTRAN77 version by Jorge More, Burton Garbow, Kenneth Hillstrom.
!    FORTRAN90 version by John Burkardt.
!
!  Reference:
!
!    Jorge More, Burton Garbow, Kenneth Hillstrom,
!    User Guide for MINPACK-1,
!    Technical Report ANL-80-74,
!    Argonne National Laboratory, 1980.
!
!  Parameters:
!
!    Input, integer (kind = 4) N, is the length of the vector.
!
!    Input, real (kind = 8) X(N), the vector whose norm is desired.
!
!    Output, real (kind = 8) ENORM, the Euclidean norm of the vector.
!
  implicit none
  integer ( kind = 4 ) n
  real ( kind = 8 ) x(n)
  real ( kind = 8 ) enorm
  enorm = sqrt ( sum ( x(1:n) ** 2 ))
  return
endfunction enorm
Call graph
dogleg calls enorm
hybrd calls enorm, dogleg, qrfac
hybrj calls enorm, dogleg, qrfac
lmder calls enorm, lmpar, qrfac
lmdif calls enorm, lmpar, qrfac
lmpar calls enorm
lmstr calls enorm, lmpar, qrfac
qrfac calls enorm
hybrd1 calls hybrd
hybrj1 calls hybrj
lmder1 calls lmder
lmdif1 calls lmdif
lmstr1 calls lmstr
qform_test calls qrfac
hybrd1_test calls hybrd1
hybrj1_test calls hybrj1
lmder1_2_test calls lmder1
lmder1_test calls lmder1
lmdif1_2_test calls lmdif1
lmdif1_test calls lmdif1
lmstr1_2_test calls lmstr1
lmstr1_test calls lmstr1
test_minpack calls qform_test, hybrd1_test, hybrj1_test, lmder1_2_test, lmder1_test, lmdif1_2_test, lmdif1_test, lmstr1_2_test, lmstr1_test