free_superlu – TOOLIB
free_superlu Subroutine
4 statements
Source File
public subroutine free_superlu()
Subroutine that actually does nothing yet. Maybe, there will be extra memory that could be released here?
Arguments
None
Called by
Source Code
   subroutine free_superlu()
   !! Subroutine that actually does nothing yet. Maybe, there will be extra memory that
   !! could be released here?
   implicit none
   return
   endsubroutine free_superlu
Call graph
freefact_solver calls free_superlu
solve_syst calls freefact_solver, solution_solver
solution_solver calls solve_syst
test_solvers calls solve_syst