genrand64_real1 – TOOLIB
genrand64_real1 Function
5 statements
Source File
private function genrand64_real1(me)
Generates a random number on [0,1]-real-interval
Type Bound
mt19937
Arguments
Type Intent Optional Attributes Name
class(mt19937), intent(inout) :: me
Return Value real(kind=r8)
Calls
Called by
Source Code
  real(r8) function genrand64_real1(me)
    !! Generates a random number on [0,1]-real-interval
    implicit none
    class(mt19937),intent(inout) :: me
    genrand64_real1 = real(ishft(me%genrand64_int64(), -11), kind=r8) * pi253_1
  end function genrand64_real1
Call graph
genrand64_real1 calls genrand64_int64
genrand64_int64 calls init_genrand64
urand calls genrand64_real1
cross calls urand
mutate calls urand
pikaia calls urand, cross, mutate, select_parents, stdrep
select_parents calls urand
stdrep calls urand
solve_with_pikaia calls pikaia
test_algen calls solve_with_pikaia