get_unit – TOOLIB
get_unit Subroutine
20 statements
Source File
private subroutine get_unit(iunit)
GET_UNIT returns a free FORTRAN unit number.
Arguments
Type Intent Optional Attributes Name
integer :: iunit
Called by
Source Code
subroutine get_unit (iunit)
!
!*******************************************************************************
!
!! GET_UNIT returns a free FORTRAN unit number.
!
!
!  Discussion:
!
!    A "free" FORTRAN unit number is an integer between 1 and 99 which
!    is not currently associated with an I/O device.  A free FORTRAN unit
!    number is needed in order to open a file with the OPEN command.
!
!  Modified:
!
!    02 March 1999
!
!  Author:
!
!    John Burkardt
!
!  Parameters:
!
!    Output, integer IUNIT.
!
!    If IUNIT = 0, then no free FORTRAN unit could be found, although
!    all 99 units were checked (except for units 5 and 6).
!
!    Otherwise, IUNIT is an integer between 1 and 99, representing a
!    free FORTRAN unit.  Note that GET_UNIT assumes that units 5 and 6
!    are special, and will never return those values.
!
  implicit none
!
  integer i
  integer ios
  integer iunit
  logical lopen
  iunit = 0
  do i = 1, 99
    if ( i /= 5 .and. i /= 6 ) then
      inquire ( unit = i, opened = lopen, iostat = ios )
      if ( ios == 0 ) then
        if ( .not. lopen ) then
          iunit = i
          return
        end if
      end if
    end if
  end do
  return
endsubroutine get_unit
Call graph
write_polar_data calls get_unit
write_polar_plot calls get_unit
write_vector_data calls get_unit
write_vector_plot calls get_unit
write_xy2_data calls get_unit
write_xy2_plot calls get_unit
write_xy_data calls get_unit
write_xy_plot calls get_unit
write_xyy_data calls get_unit
write_xyy_plots calls get_unit
write_xyz_data calls get_unit
write_xyz_plot calls get_unit
write_xyzgrid_contour calls get_unit
write_xyzgrid_data calls get_unit
write_xyzgrid_surface calls get_unit
write_y_plot calls get_unit
test01 calls write_xy_data, write_xy_plot
test02 calls write_xyy_data, write_xyy_plots
test03 calls write_xyz_data, write_xyz_plot
test04 calls write_vector_data, write_vector_plot
test05 calls write_xyzgrid_data, write_xyzgrid_surface
test06 calls write_xyzgrid_contour, write_xyzgrid_data
test_gnufor calls test01, test02, test03, test04, test05, test06