hybrd1_f – TOOLIB
hybrd1_f Subroutine
12 statements
Source File
subroutine hybrd1_f(n, x, fvec, iflag)
HYBRD1_F is a function routine for use with HYBRD1_TEST.
Arguments
Type Intent Optional Attributes Name
integer :: n
real(kind=rk) :: x(n)
real(kind=rk) :: fvec(n)
integer :: iflag
Called by
Call graph
hybrd1_test calls hybrd1_f
hybrj1_test calls hybrd1_f
test_minpack calls hybrd1_test, hybrj1_test