init_superlu – TOOLIB
init_superlu Subroutine
6 statements
Source File
public subroutine init_superlu(sulu)
Note
Arguments
Type Intent Optional Attributes Name
type(SULU_ENV), intent(inout) :: sulu
Calls
Called by
Source Code
   subroutine init_superlu(sulu)
   implicit none
   type(SULU_ENV), intent(inout) :: sulu
      call set_default_options(sulu%options)
   return
   endsubroutine init_superlu
Call graph
init_superlu calls set_default_options
init_solver calls init_superlu
solve_syst calls init_solver, solution_solver
solution_solver calls solve_syst
test_solvers calls solve_syst