init_fftw3_real – TOOLIB
init_fftw3_real Subroutine
11 statements
Source File
public subroutine init_fftw3_real(long, larg, plan_flag)
Subroutine to initialize the FFTW3 process 1 FFT distributed on several threads Real case.
Arguments
Type Intent Optional Attributes Name
integer(kind=I4), intent(in) :: long
first 2D array dimension
integer(kind=I4), intent(in) :: larg
second 2D array dimension
integer(kind=I4), intent(in) :: plan_flag
planning option, FFTW_ESTIMATE for example
Calls
Called by
Source Code
   subroutine init_fftw3_real(long, larg, plan_flag)
   !! Subroutine to initialize the FFTW3 process *1 FFT distributed on several threads*
   !! Real case.
   implicit none
   integer(kind=I4), intent(in) :: long      !! *first  2D array dimension*
   integer(kind=I4), intent(in) :: larg      !! *second 2D array dimension*
   integer(kind=I4), intent(in) :: plan_flag !! *planning option, [[fftw3(module):FFTW_ESTIMATE]] for example*
      call alloc_fftw3_real(long, larg)
      call make_plan_fftw3_real(long, larg, plan_flag)
      SINGL_FFTW_ALLOCATED = .true.
      FFT_DIM(1:2) = [long, larg]
   return
   endsubroutine init_fftw3_real
Call graph
init_fftw3_real calls alloc_fftw3_real, make_plan_fftw3_real
alloc_fftw3_real calls fftw_alloc_complex, fftw_alloc_real
make_plan_fftw3_real calls fftw_plan_dft_c2r_2d, fftw_plan_dft_r2c_2d
calc_fftw3_real_bwd calls init_fftw3_real
calc_fftw3_real_fwd calls init_fftw3_real
test_fftw3 calls init_fftw3_real, calc_fftw3_real_bwd, calc_fftw3_real_fwd