init_order – TOOLIB
init_order Subroutine
8 statements
Source File
public subroutine init_order(order, n)
Vector initialization: 1 … n
Arguments
Type Intent Optional Attributes Name
integer(kind=I4), intent(out), dimension(n) :: order
order vector
integer(kind=I4), intent(in) :: n
size of the vector
Called by
Source Code
   subroutine init_order(order, n)
   !! Vector initialization: 1 ... n
   implicit none
   integer(kind=I4), intent(in)                :: n      !! *size of the vector*
   integer(kind=I4), dimension(n), intent(out) :: order  !! *order vector*
      integer(kind=I4) :: i
      order = [ integer(kind=I4) :: (i, i = 1, n) ]
   return
   endsubroutine init_order
Call graph
sort_array2 calls init_order
main calls init_order, sort_array2
from_elemental_to_assembled calls sort_array2
melange calls sort_array2
read_surf calls sort_array2
convert_matrice_format calls from_elemental_to_assembled
test_algen calls melange
test_surfile calls read_surf
test_solvers calls convert_matrice_format