init_genrand64 – TOOLIB
init_genrand64 Subroutine
11 statements
Source File
private subroutine init_genrand64(me, seed)
Initializes me%mt(nn) with a seed
Type Bound
mt19937
Arguments
Type Intent Optional Attributes Name
class(mt19937), intent(inout) :: me
integer(kind=i8), intent(in) :: seed
Called by
Source Code
  subroutine init_genrand64(me,seed)
    !! Initializes `me%mt(nn)` with a seed
    implicit none
    class(mt19937),intent(inout) :: me
    integer(i8), intent(in) :: seed
    integer :: i
    me%mt(1) = seed
    do i = 1, nn-1
      me%mt(i+1) = 6364136223846793005_i8 * ieor(me%mt(i), ishft(me%mt(i), -62)) + i
    end do
    me%mti = nn
  end subroutine init_genrand64
Call graph
genrand64_int64 calls init_genrand64
init_by_array64 calls init_genrand64
genrand64_real1 calls genrand64_int64
genrand64_real2 calls genrand64_int64
genrand64_real3 calls genrand64_int64
init_genrand64_i4 calls initialize
rninit calls initialize
pikaia calls rninit, urand, cross, mutate, select_parents, stdrep
urand calls genrand64_real1
cross calls urand
mutate calls urand
select_parents calls urand
solve_with_pikaia calls pikaia
stdrep calls urand
test_algen calls solve_with_pikaia