is_linux – TOOLIB
is_linux Function
7 statements
Source File
public function is_linux()
Function that returns true if the operating system is linux
Arguments
None
Return Value logical(kind=4)
Called by
Call graph
dir_separator calls is_linux
dirname calls dir_separator
filename calls dir_separator
make_path calls dir_separator
path2vec calls dir_separator
vec2path calls dir_separator
test_files calls dir_separator, filename, make_path, path2vec, vec2path