lmder1_test – TOOLIB
lmder1_test Subroutine
28 statements
Source File
subroutine lmder1_test()
LMDER1_TEST tests LMDER1.
Arguments
None
Calls
Called by
Call graph
lmder1_test calls lmder1, lmder1_f, r8vec_print
lmder1 calls lmder
lmder calls enorm, lmpar, qrfac
lmpar calls enorm, qrsolv
qrfac calls enorm
test_minpack calls lmder1_test