lmdif1_2_test – TOOLIB
lmdif1_2_test Subroutine
26 statements
Source File
subroutine lmdif1_2_test()
LMDIF1_2_TEST tests LMDIF1.
Arguments
None
Calls
Called by
Call graph
lmdif1_2_test calls lmdif1, lmdif1_2_f, r8vec_print
lmdif1 calls lmdif
lmdif calls enorm, fdjac2, lmpar, qrfac
lmpar calls enorm, qrsolv
qrfac calls enorm
test_minpack calls lmdif1_2_test