lmstr1_2_test – TOOLIB
lmstr1_2_test Subroutine
29 statements
Source File
subroutine lmstr1_2_test()
LMSTR1_2_TEST tests LMSTR1.
Arguments
None
Calls
Called by
Call graph
lmstr1_2_test calls lmstr1, lmstr1_2_f, r8vec_print
lmstr1 calls lmstr
lmstr calls enorm, lmpar, qrfac, rwupdt
lmpar calls enorm, qrsolv
qrfac calls enorm
test_minpack calls lmstr1_2_test