make_path – TOOLIB
make_path Subroutine
14 statements
Source File
public subroutine make_path(wkd, file_path, exit_status)
Subroutine that creates the folders of a file path
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: wkd
character(len=*), intent(in) :: file_path
integer(kind=I4), intent(out) :: exit_status
Calls
Called by
Source Code
   subroutine make_path(wkd, file_path, exit_status)
   !! Subroutine that creates the folders of a file path
   implicit none
   character(len = *), intent(in ) :: wkd
   character(len = *), intent(in ) :: file_path
   integer(kind = I4), intent(out) :: exit_status
      character(len = 512) :: dir
      character(len =   1) :: sep
      integer(kind = I4)   :: isep
      sep = dir_separator()
      isep = index( file_path, sep, back = .true. )
      dir = file_path(1:isep - 1)
      call mkdir(wkd = wkd, directory = trim(dir), sep = sep, exit_status = exit_status)
   return
   endsubroutine make_path
Call graph
make_path calls dir_separator, mkdir
dir_separator calls is_linux
test_files calls make_path