melange – TOOLIB
melange Subroutine
10 statements
Source File
subroutine melange(tab, lg)
Arguments
Type Intent Optional Attributes Name
real(kind=r8), intent(inout), dimension(1:lg) :: tab
integer(kind=i4), intent(in) :: lg
Calls
Called by
Source Code
   subroutine melange(tab, lg)
   implicit none
   integer(kind=i4), intent(in   )                  :: lg
   real(kind=r8)   , intent(inout), dimension(1:lg) :: tab
      real(kind=r8), dimension(1:lg) :: tmp
      integer(kind=i4) :: i
      call random_number(harvest=tmp)
      call sort_array2(tab_inout = tmp(1:lg),            &  !
                            tab1 = tab(1:lg), n = lg)       !
   return
   endsubroutine melange
Call graph
melange calls sort_array2
sort_array2 calls change_array_order, init_order, sort_array_integer_with_order, sort_array_real_with_order
sort_array_integer_with_order calls sort_array_integer_with_order
sort_array_real_with_order calls sort_array_real_with_order
test_algen calls melange