r8vec_print – TOOLIB
r8vec_print Subroutine
14 statements
Source File
public subroutine r8vec_print(n, a, title)
R8VEC_PRINT prints an R8VEC.
Arguments
Type Intent Optional Attributes Name
integer(kind=4) :: n
real(kind=8) :: a(n)
character(len=*) :: title
Called by
Source Code
subroutine r8vec_print (n, a, title)
!*****************************************************************************80
!
!! R8VEC_PRINT prints an R8VEC.
!
!  Discussion:
!
!    An R8VEC is a vector of R8's.
!
!  Licensing:
!
!    This code may freely be copied, modified, and used for any purpose.
!
!  Modified:
!
!    22 August 2000
!
!  Author:
!
!    John Burkardt
!
!  Parameters:
!
!    Input, integer (kind = 4) N, the number of components of the vector.
!
!    Input, real (kind = 8) A(N), the vector to be printed.
!
!    Input, character (len = *) TITLE, a title.
!
  implicit none
  integer ( kind = 4 ) n
  real ( kind = 8 ) a(n)
  integer ( kind = 4 ) i
  character ( len = * ) title
  write ( *, '(a)' ) ' '
  write ( *, '(a)' ) trim ( title )
  write ( *, '(a)' ) ' '
  do i = 1, n
    write ( *, '(2x,i8,2x,g16.8)' ) i, a(i)
  end do
  return
endsubroutine r8vec_print
Call graph
chkder_test calls r8vec_print
hybrd1_test calls r8vec_print
hybrj1_test calls r8vec_print
lmder1_2_test calls r8vec_print
lmder1_test calls r8vec_print
lmdif1_2_test calls r8vec_print
lmdif1_test calls r8vec_print
lmstr1_2_test calls r8vec_print
lmstr1_test calls r8vec_print
test_minpack calls chkder_test, hybrd1_test, hybrj1_test, lmder1_2_test, lmder1_test, lmdif1_2_test, lmdif1_test, lmstr1_2_test, lmstr1_test