s_umfpack_ci_solve – TOOLIB
s_umfpack_ci_solve Subroutine
13 statements
Source File
public subroutine s_umfpack_ci_solve(sys, Ap, Ai, Ax, Xx, Bx, Numeric, Control, Info, status)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), optional :: sys
integer, intent(in), optional :: Ap(*)
integer, intent(in), optional :: Ai(*)
complex(kind=r8), intent(in), optional :: Ax(*)
complex(kind=r8), intent(out) :: Xx(*)
complex(kind=r8), intent(in) :: Bx(*)
type(c_ptr), intent(in), optional :: Numeric
real(kind=r8), optional :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8), optional :: Info(0:UMFPACK_INFO-1)
integer, optional :: status
Calls
Called by
Call graph
s_umfpack_ci_solve calls umfpack_ci_solve
umfpack_ci_solve calls c_umfpack_zi_solve
s_umfpack_solve calls s_umfpack_ci_solve, s_umfpack_zi_solve
s_umfpack_zi_solve calls s_umfpack_ci_solve, s_umfpack_zi_solve
umf4csol_ip calls s_umfpack_ci_solve
umfpack_ci_operator_csc calls s_umfpack_ci_solve
umfpack_ci_operator_csr calls s_umfpack_ci_solve
umfpack_ci_operator_pcsc calls s_umfpack_ci_solve
umfpack_ci_operator_pcsr calls s_umfpack_ci_solve
operator(.umfpack.) calls umfpack_ci_operator_csc, umfpack_ci_operator_csr, umfpack_ci_operator_pcsc, umfpack_ci_operator_pcsr, umfpack_zi_operator_csc, umfpack_zi_operator_csr, umfpack_zi_operator_pcsc, umfpack_zi_operator_pcsr
umf4csol calls umf4csol_ip, umf4csol, s_umfpack_solve
umf4sol calls umf4csol_ip, umf4csol, umf4sol, umf4zsol, umf4sol_ip, umf4zsol_ip, s_umfpack_solve
umf4zsol calls umf4csol_ip, umf4csol, umf4zsol, umf4zsol_ip, s_umfpack_solve
umf4csolr calls s_umfpack_solve, umf4csolr_ip, umf4csolr
umf4csolr_ip calls s_umfpack_solve
umf4sol_ip calls s_umfpack_solve
umf4solr calls s_umfpack_solve, umf4csolr_ip, umf4solr_ip, umf4zsolr_ip, umf4csolr, umf4solr, umf4zsolr
umf4solr_ip calls s_umfpack_solve
umf4zsol_ip calls s_umfpack_zi_solve
umf4zsolr calls s_umfpack_solve, umf4csolr_ip, umf4zsolr_ip, umf4csolr, umf4zsolr
umf4zsolr_ip calls s_umfpack_solve
umfpack_zi_operator_csc calls s_umfpack_zi_solve
umfpack_zi_operator_csr calls s_umfpack_zi_solve
umfpack_zi_operator_pcsc calls s_umfpack_zi_solve
umfpack_zi_operator_pcsr calls s_umfpack_zi_solve