s_umfpack_di_symbolic – TOOLIB
s_umfpack_di_symbolic Subroutine
11 statements
Source File
public subroutine s_umfpack_di_symbolic(n_row, n_col, Ap, Ai, Ax, Symbolic, Control, Info, status)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n_row
integer, intent(in) :: n_col
integer, intent(in) :: Ap(*)
integer, intent(in) :: Ai(*)
real(kind=r8), intent(in), optional :: Ax(*)
type(c_ptr), optional :: Symbolic
real(kind=r8), optional :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8), optional :: Info(0:UMFPACK_INFO-1)
integer, optional :: status
Calls
Called by
Call graph
s_umfpack_di_symbolic calls umfpack_di_symbolic
umfpack_di_symbolic calls c_umfpack_di_symbolic
s_umfpack_symbolic calls s_umfpack_di_symbolic
analyse_solver calls s_umfpack_di_symbolic
umfpack_di_operator_csc calls s_umfpack_di_symbolic
umfpack_di_operator_csr calls s_umfpack_di_symbolic
umfpack_di_operator_pcsc calls s_umfpack_di_symbolic
umfpack_di_operator_pcsr calls s_umfpack_di_symbolic
operator(.umfpack.) calls umfpack_di_operator_csc, umfpack_di_operator_csr, umfpack_di_operator_pcsc, umfpack_di_operator_pcsr
solve_syst calls analyse_solver, solution_solver
umf4csym calls s_umfpack_symbolic, umf4csym_ip, umf4csym
umf4csym_ip calls s_umfpack_symbolic
umf4sym calls s_umfpack_symbolic, umf4csym_ip, umf4sym_ip, umf4zsym_ip, umf4csym, umf4sym, umf4zsym
umf4sym_ip calls s_umfpack_symbolic
umf4zsym calls s_umfpack_symbolic, umf4csym_ip, umf4zsym_ip, umf4csym, umf4zsym
umf4zsym_ip calls s_umfpack_symbolic
solution_solver calls solve_syst
test_solvers calls solve_syst