s_umfpack_di_solve – TOOLIB
s_umfpack_di_solve Subroutine
13 statements
Source File
public subroutine s_umfpack_di_solve(sys, Ap, Ai, Ax, X, B, Numeric, Control, Info, status)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), optional :: sys
integer, intent(in), optional :: Ap(*)
integer, intent(in), optional :: Ai(*)
real(kind=r8), intent(in), optional :: Ax(*)
real(kind=r8), intent(out) :: X(*)
real(kind=r8), intent(in) :: B(*)
type(c_ptr), intent(in), optional :: Numeric
real(kind=r8), optional :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8), optional :: Info(0:UMFPACK_INFO-1)
integer, optional :: status
Calls
Called by
Call graph
s_umfpack_di_solve calls umfpack_di_solve
umfpack_di_solve calls c_umfpack_di_solve
s_umfpack_solve calls s_umfpack_di_solve
solution_solver calls s_umfpack_di_solve, solve_syst
umfpack_di_operator_csc calls s_umfpack_di_solve
umfpack_di_operator_csr calls s_umfpack_di_solve
umfpack_di_operator_pcsc calls s_umfpack_di_solve
umfpack_di_operator_pcsr calls s_umfpack_di_solve
operator(.umfpack.) calls umfpack_di_operator_csc, umfpack_di_operator_csr, umfpack_di_operator_pcsc, umfpack_di_operator_pcsr
solve_syst calls solution_solver
umf4csol calls s_umfpack_solve
umf4csolr calls s_umfpack_solve, umf4csolr_ip, umf4csolr
umf4csolr_ip calls s_umfpack_solve
umf4sol calls s_umfpack_solve, umf4sol_ip, umf4sol
umf4sol_ip calls s_umfpack_solve
umf4solr calls s_umfpack_solve, umf4csolr_ip, umf4solr_ip, umf4zsolr_ip, umf4csolr, umf4solr, umf4zsolr
umf4solr_ip calls s_umfpack_solve
umf4zsol calls s_umfpack_solve
umf4zsolr calls s_umfpack_solve, umf4csolr_ip, umf4zsolr_ip, umf4csolr, umf4zsolr
umf4zsolr_ip calls s_umfpack_solve
test_solvers calls solve_syst