s_umfpack_di_scale – TOOLIB
s_umfpack_di_scale Subroutine
9 statements
Source File
public subroutine s_umfpack_di_scale(X, B, Numeric, status)
Arguments
Type Intent Optional Attributes Name
real(kind=r8), intent(out) :: X(*)
real(kind=r8), intent(in) :: B(*)
type(c_ptr), intent(in), optional :: Numeric
integer, optional :: status
Calls
Called by
Call graph
s_umfpack_di_scale calls umfpack_di_scale
umfpack_di_scale calls c_umfpack_di_scale
s_umfpack_scale calls s_umfpack_di_scale