s_umfpack_ci_symbolic – TOOLIB
s_umfpack_ci_symbolic Subroutine
11 statements
Source File
public subroutine s_umfpack_ci_symbolic(n_row, n_col, Ap, Ai, Ax, Symbolic, Control, Info, status)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n_row
integer, intent(in) :: n_col
integer, intent(in) :: Ap(*)
integer, intent(in) :: Ai(*)
complex(kind=r8), intent(in) :: Ax(*)
type(c_ptr), optional :: Symbolic
real(kind=r8), optional :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8), optional :: Info(0:UMFPACK_INFO-1)
integer, optional :: status
Calls
Called by
Call graph
s_umfpack_ci_symbolic calls umfpack_ci_symbolic
umfpack_ci_symbolic calls c_umfpack_zi_symbolic
s_umfpack_symbolic calls s_umfpack_ci_symbolic, s_umfpack_zi_symbolic
s_umfpack_zi_symbolic calls s_umfpack_ci_symbolic, s_umfpack_zi_symbolic
umfpack_ci_operator_csc calls s_umfpack_ci_symbolic
umfpack_ci_operator_csr calls s_umfpack_ci_symbolic
umfpack_ci_operator_pcsc calls s_umfpack_ci_symbolic
umfpack_ci_operator_pcsr calls s_umfpack_ci_symbolic
operator(.umfpack.) calls umfpack_ci_operator_csc, umfpack_ci_operator_csr, umfpack_ci_operator_pcsc, umfpack_ci_operator_pcsr, umfpack_zi_operator_csc, umfpack_zi_operator_csr, umfpack_zi_operator_pcsc, umfpack_zi_operator_pcsr
umf4csym calls s_umfpack_symbolic, umf4csym_ip, umf4csym
umf4csym_ip calls s_umfpack_symbolic
umf4sym calls s_umfpack_symbolic, umf4csym_ip, umf4sym_ip, umf4zsym_ip, umf4csym, umf4sym, umf4zsym
umf4sym_ip calls s_umfpack_symbolic
umf4zsym calls s_umfpack_symbolic, umf4csym_ip, umf4zsym_ip, umf4csym, umf4zsym
umf4zsym_ip calls s_umfpack_symbolic
umfpack_zi_operator_csc calls s_umfpack_zi_symbolic
umfpack_zi_operator_csr calls s_umfpack_zi_symbolic
umfpack_zi_operator_pcsc calls s_umfpack_zi_symbolic
umfpack_zi_operator_pcsr calls s_umfpack_zi_symbolic