s_umfpack_ci_numeric – TOOLIB
s_umfpack_ci_numeric Subroutine
11 statements
Source File
public subroutine s_umfpack_ci_numeric(Ap, Ai, Ax, Symbolic, Numeric, Control, Info, status)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: Ap(*)
integer, intent(in) :: Ai(*)
complex(kind=r8), intent(in) :: Ax(*)
type(c_ptr), intent(in), optional :: Symbolic
type(c_ptr), optional :: Numeric
real(kind=r8), optional :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8), optional :: Info(0:UMFPACK_INFO-1)
integer, optional :: status
Calls
Called by
Call graph
s_umfpack_ci_numeric calls umfpack_ci_numeric
umfpack_ci_numeric calls c_umfpack_zi_numeric
s_umfpack_numeric calls s_umfpack_ci_numeric, s_umfpack_zi_numeric
s_umfpack_zi_numeric calls s_umfpack_ci_numeric, s_umfpack_zi_numeric
umfpack_ci_operator_csc calls s_umfpack_ci_numeric
umfpack_ci_operator_csr calls s_umfpack_ci_numeric
umfpack_ci_operator_pcsc calls s_umfpack_ci_numeric
umfpack_ci_operator_pcsr calls s_umfpack_ci_numeric
operator(.umfpack.) calls umfpack_ci_operator_csc, umfpack_ci_operator_csr, umfpack_ci_operator_pcsc, umfpack_ci_operator_pcsr, umfpack_zi_operator_csc, umfpack_zi_operator_csr, umfpack_zi_operator_pcsc, umfpack_zi_operator_pcsr
umf4cnum calls s_umfpack_numeric, umf4cnum_ip, umf4cnum
umf4cnum_ip calls s_umfpack_numeric
umf4num calls s_umfpack_numeric, umf4cnum_ip, umf4num_ip, umf4znum_ip, umf4cnum, umf4num, umf4znum
umf4num_ip calls s_umfpack_numeric
umf4znum calls s_umfpack_numeric, umf4cnum_ip, umf4znum_ip, umf4cnum, umf4znum
umf4znum_ip calls s_umfpack_numeric
umfpack_zi_operator_csc calls s_umfpack_zi_numeric
umfpack_zi_operator_csr calls s_umfpack_zi_numeric
umfpack_zi_operator_pcsc calls s_umfpack_zi_numeric
umfpack_zi_operator_pcsr calls s_umfpack_zi_numeric