solution_solver – TOOLIB
solution_solver Subroutine
35 statements
Source File
private subroutine solution_solver(mat)
Subroutine to solve the system (sparse A)
Arguments
Type Intent Optional Attributes Name
type(MAT_SOLV), intent(inout), target :: mat
high level system type
Calls
Called by
Source Code
   subroutine solution_solver(mat)
   !! Subroutine to solve the system \([A]\{x\} = \{b\}\) (sparse A)
   implicit none
   type(MAT_SOLV), target, intent(inout) :: mat   !! *high level system type*
      integer(kind=I4) :: ierr
      select case(mat%slv_t)
         case(MA48)
#if WITH_MA48
            call ma48_solve(matrix = mat%matma48%zmat,   &
                           factors = mat%matma48%fact,   &
                               rhs = mat%b,              &
                                 x = mat%x,              &
                           control = mat%matma48%ctrl,   &
                             sinfo = mat%matma48%sinf,   &
                             resid = mat%matma48%resid,  &
                             error = mat%error)
#else
   stop 'MA48_LIB not defined'
#endif
         case(MUMP)
            mat%matmump%job = 3
            call dmumps(mat%matmump)
            if (mat%matmump%infog(1) < 0) then
               write(OPU,'(a,a,i6,a,i9)') ' error return: ',                              &
                                          '  mumps_par%infog(1)= ', mat%matmump%infog(1), &
                                          '  mumps_par%infog(2)= ', mat%matmump%infog(2)
               call mpi_finalize(ierr)
               stop 'Error in SOLUTION_SOLVER'
            endif
            ! solution has been assembled on the host
            if ( mat%matmump%myid == 0 ) then
               mat%x(1:mat%nn) = mat%matmump%rhs(1:mat%nn)
            endif
         case(SULU)
            call solv_superlu(sol_x = mat%x,        &
                              sulu  = mat%matsulu,  &
                           verbose  = (mat%matsulu%options%PrintStat==1))
            mat%matsulu%first = .false.
         case(UMFP)
            ! Numeric factors must exist
            if (.not.C_ASSOCIATED(mat%matumfp%c_numeric)) call solve_syst(mat, 'fac')
            mat%matumfp%c_control(UMFPACK_IRSTEP) = 0 ! solve ax=b, without iterative refinement
            ! If you want to evaluate the required RAM (Go)
            ! write(*,*) mat%matumfp%c_info(UMFPACK_PEAK_MEMORY_ESTIMATE)/mat%matumfp%c_info(UMFPACK_SIZE_OF_UNIT)/1e9
            ! write(*,*) sizeof(mat%a_elt)/1e9
            call s_umfpack_di_solve(sys = UMFPACK_A,              &
                                      x = mat%x,                  &
                                      b = mat%b,                  &
                                numeric = mat%matumfp%c_numeric,  &
                                control = mat%matumfp%c_control,  &
                                   info = mat%matumfp%c_info)
            if (mat%matumfp%c_info(UMFPACK_STATUS) < 0) then
               write(OPU, *) 'error occurred in umfpack_di_solve: ', mat%matumfp%c_info(UMFPACK_STATUS)
               stop 'Error in SOLUTION_SOLVER'
            endif
         case default
            stop 'Unknown solver type, SOLUTION_SOLVER'
      endselect
   return
   endsubroutine solution_solver
Call graph
solution_solver calls dmumps, infog, ma48_solve, mpi_finalize, s_umfpack_di_solve, solv_superlu, solve_syst, rhs
s_umfpack_di_solve calls umfpack_di_solve
solv_superlu calls destroy_compcol_matrix, destroy_supernode_matrix, dgssvx, statfree, statinit, statprint, prep_superlu
solve_syst calls solution_solver, analyse_solver, close_solver, factorize_solver, freefact_solver, init_solver
analyse_solver calls dmumps, prep_superlu, ma48_analyse, s_umfpack_di_symbolic
close_solver calls dmumps, infog, mpi_finalize, ma48_finalize, close_superlu, umfpack_di_free_numeric, umfpack_di_free_symbolic, umfpack_di_report_info
factorize_solver calls dmumps, ma48_factorize, fact_superlu, s_umfpack_di_numeric, umfpack_di_free_numeric
freefact_solver calls free_superlu, umfpack_di_free_numeric
init_solver calls dmumps, infog, mpi_finalize, icntl, ma48_initialize, mpi_init, init_superlu, umfpack_di_defaults, umfpack_di_report_control
prep_superlu calls dcreate_compcol_matrix, dcreate_dense_matrix
umfpack_di_solve calls c_umfpack_di_solve
close_superlu calls destroy_compcol_matrix, destroy_dense_matrix
fact_superlu calls dgssvx, statfree, statinit, statprint
init_superlu calls set_default_options
s_umfpack_di_numeric calls umfpack_di_numeric
s_umfpack_di_symbolic calls umfpack_di_symbolic
umfpack_di_defaults calls c_umfpack_di_defaults
umfpack_di_free_numeric calls c_umfpack_di_free_numeric
umfpack_di_free_symbolic calls c_umfpack_di_free_symbolic
umfpack_di_report_control calls c_umfpack_di_report_control
umfpack_di_report_info calls c_umfpack_di_report_info
umfpack_di_numeric calls c_umfpack_di_numeric
umfpack_di_symbolic calls c_umfpack_di_symbolic
test_solvers calls solve_syst