solve_syst – TOOLIB
solve_syst Subroutine
37 statements
Source File
public subroutine solve_syst(mat, step)
Note
General hat subroutine that handles the resolution steps:
ini solver initialization
ana solver analyzis when it’s proposed by the solver
fac solver factorization
sol solver solution
fre solver memory release when it’s proposed by the solver
end solver end
Arguments
Type Intent Optional Attributes Name
type(MAT_SOLV), intent(inout) :: mat
high level system type
character(len=*), intent(in) :: step
‘ini’=initialize, ‘ana’=analyze, ‘fac’=factorize, ‘sol’=solve, ‘fre’=free memory, ‘end’=close solver
Calls
Called by
Source Code
   subroutine solve_syst(mat, step)
   implicit none
   type(MAT_SOLV), intent(inout) :: mat   !! *high level system type*
   character(len=*), intent(in)  :: step  !! *'ini'=initialize, 'ana'=analyze, 'fac'=factorize, 'sol'=solve, 'fre'=free memory, 'end'=close solver*
      if ( index(step, 'ini')/=0 ) then ; call init_solver(     mat) ; mat%ini = .true. ; return ; endif
      if ( index(step, 'ana')/=0 ) then ; call analyse_solver(  mat) ; mat%ana = .true. ; return ; endif
      if ( index(step, 'fac')/=0 ) then ; call factorize_solver(mat) ; mat%fac = .true. ; return ; endif
      if ( index(step, 'sol')/=0 ) then ; call solution_solver( mat) ; mat%sol = .true. ; return ; endif
      if ( index(step, 'fre')/=0 ) then ; call freefact_solver( mat) ; mat%fre = .true. ; return ; endif
      if ( index(step, 'end')/=0 ) then ; call close_solver( mat)    ; mat%end = .true. ; return ; endif
      stop 'Bad step chosen in SOLVE_SYST'
   return
   endsubroutine solve_syst
Call graph
solve_syst calls analyse_solver, close_solver, factorize_solver, freefact_solver, init_solver, solution_solver
analyse_solver calls dmumps, ma48_analyse, prep_superlu, s_umfpack_di_symbolic
close_solver calls dmumps, infog, ma48_finalize, mpi_finalize, close_superlu, umfpack_di_free_numeric, umfpack_di_free_symbolic, umfpack_di_report_info
factorize_solver calls dmumps, ma48_factorize, fact_superlu, s_umfpack_di_numeric, umfpack_di_free_numeric
freefact_solver calls free_superlu, umfpack_di_free_numeric
init_solver calls dmumps, icntl, infog, ma48_initialize, mpi_finalize, mpi_init, init_superlu, umfpack_di_defaults, umfpack_di_report_control
solution_solver calls solve_syst, dmumps, infog, ma48_solve, mpi_finalize, s_umfpack_di_solve, solv_superlu, rhs
close_superlu calls destroy_compcol_matrix, destroy_dense_matrix
fact_superlu calls dgssvx, statfree, statinit, statprint
init_superlu calls set_default_options
prep_superlu calls dcreate_compcol_matrix, dcreate_dense_matrix
s_umfpack_di_numeric calls umfpack_di_numeric
s_umfpack_di_solve calls umfpack_di_solve
s_umfpack_di_symbolic calls umfpack_di_symbolic
solv_superlu calls prep_superlu, destroy_compcol_matrix, destroy_supernode_matrix, dgssvx, statfree, statinit, statprint
umfpack_di_defaults calls c_umfpack_di_defaults
umfpack_di_free_numeric calls c_umfpack_di_free_numeric
umfpack_di_free_symbolic calls c_umfpack_di_free_symbolic
umfpack_di_report_control calls c_umfpack_di_report_control
umfpack_di_report_info calls c_umfpack_di_report_info
umfpack_di_numeric calls c_umfpack_di_numeric
umfpack_di_solve calls c_umfpack_di_solve
umfpack_di_symbolic calls c_umfpack_di_symbolic
test_solvers calls solve_syst