sort_array_real_with_order – TOOLIB
sort_array_real_with_order Subroutine
35 statements
Source File
private recursive subroutine sort_array_real_with_order(g, d, rtabref, order)
Sort a vector of reals and store the order
Arguments
Type Intent Optional Attributes Name
integer(kind=I4), intent(in) :: g
left index
integer(kind=I4), intent(in) :: d
right index
real(kind=R8), intent(inout), dimension(:) :: rtabref
vector to sort
integer(kind=I4), intent(inout), dimension(:) :: order
sort order
Called by
Source Code
   recursive subroutine sort_array_real_with_order(g, d, rtabref, order)
   !! Sort a vector of reals and store the order
   implicit none
   integer(kind=I4), intent(in)                  :: g          !! *left index*
   integer(kind=I4), intent(in)                  :: d          !! *right index*
   real(kind=R8),    intent(inout), dimension(:) :: rtabref    !! *vector to sort*
   integer(kind=I4), intent(inout), dimension(:) :: order      !! *sort order*
      integer(kind=I4) :: i, j, mil, itmp
      real(kind=R8)    :: tmp, cle
      i = g
      j = d
      mil = (g+d)/2
      cle = rtabref(mil)
      if (g>=d) return
      do while (i<=j)
         do while (rtabref(i)<cle)
            i = i + 1
         enddo
         do while (rtabref(j)>cle)
            j = j - 1
         enddo
         if (i<=j) then
            ! échange des éléments du tableau
            tmp = rtabref(i)
            rtabref(i) = rtabref(j)
            rtabref(j) = tmp
            ! échange des éléments du tableau
            itmp     = order(i)
            order(i) = order(j)
            order(j) = itmp
            ! échange des éléments du vecteur position
            i = i + 1
            j = j - 1
         endif
      enddo
      if (g<j) call sort_array_real_with_order(g, j, rtabref, order)
      if (d>i) call sort_array_real_with_order(i, d, rtabref, order)
   return
   endsubroutine sort_array_real_with_order
Call graph
sort_array_real_with_order calls sort_array_real_with_order
sort_array2 calls sort_array_real_with_order
from_elemental_to_assembled calls sort_array2
melange calls sort_array2
read_surf calls sort_array2
main calls sort_array2
convert_matrice_format calls from_elemental_to_assembled
test_algen calls melange
test_surfile calls read_surf
test_solvers calls convert_matrice_format