tab_tcheby – TOOLIB
tab_tcheby Subroutine
17 statements
Source File
public subroutine tab_tcheby(deg, nx, vec_x, tab_tche)
Note
Valeurs tabulées de polynômes de Tchebychev
On se donne des points xi le long d’UN axe et on calcule les valeurs d’un polynôme de Tchebychev de degré j en ces points.
Arguments
Type Intent Optional Attributes Name
integer(kind=I4), intent(in) :: deg
degré max du polynôme
integer(kind=I4), intent(in) :: nx
nbre de points de calcul
real(kind=R8), intent(in), dimension(1:nx) :: vec_x
vecteur des points de calcul
real(kind=R8), intent(out), allocatable, dimension(:,:) :: tab_tche
tableau des valeurs calculées
Calls
Called by
Source Code
   subroutine tab_tcheby(deg, nx, vec_x, tab_tche)
   implicit none
   integer(kind=I4), intent(in ) :: deg                                       !! *degré max du polynôme*
   integer(kind=I4), intent(in ) :: nx                                        !! *nbre de points de calcul*
   real(kind=R8),    intent(in ), dimension(1:nx) :: vec_x                    !! *vecteur des points de calcul*
   real(kind=R8),    intent(out), allocatable, dimension(:,:)   :: tab_tche   !! *tableau des valeurs calculées*
      integer(kind=I4) :: i, j
      real(kind=R8)    :: xi
      allocate( tab_tche(1:nx, 1:deg+1) )
      do i = 1, nx
         xi = vec_x(i) ! points de l'axe
         do j = 0, deg ! pour UN degré de polynôme donné, valeurs en ces points
            tab_tche(i, j+1) = tcheby(j, xi)
         enddo
      enddo
   return
   endsubroutine tab_tcheby
Call graph
tab_tcheby calls tcheby
least_squares_tcheby calls tab_tcheby
test_tchebychev calls least_squares_tcheby