umf4pcon – TOOLIB
umf4pcon Subroutine
4 statements
Source File
public subroutine umf4pcon(Control)
Arguments
Type Intent Optional Attributes Name
real(kind=r8) :: Control(0:UMFPACK_CONTROL-1)
Calls
Call graph
umf4pcon calls umfpack_report_control
umfpack_report_control calls umfpack_di_report_control, umfpack_zi_report_control
umfpack_di_report_control calls c_umfpack_di_report_control
umfpack_zi_report_control calls c_umfpack_zi_report_control