umf4csol_ip – TOOLIB
umf4csol_ip Subroutine
13 statements
Source File
public subroutine umf4csol_ip(sys, x, b, Numeric, Control, Info)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: sys
complex(kind=r8), intent(out) :: x(*)
complex(kind=r8), intent(in) :: b(*)
integer(kind=ip) :: Numeric
real(kind=r8) :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8) :: Info(0:UMFPACK_INFO-1)
Calls
Called by
Call graph
umf4csol_ip calls s_umfpack_ci_solve
s_umfpack_ci_solve calls umfpack_ci_solve
umfpack_ci_solve calls c_umfpack_zi_solve
umf4csol calls umf4csol_ip, umf4csol
umf4sol calls umf4csol_ip, umf4csol, umf4sol, umf4zsol
umf4zsol calls umf4csol_ip, umf4csol, umf4zsol