umf4zdef – TOOLIB
umf4zdef Subroutine
4 statements
Source File
public subroutine umf4zdef(Control)
Arguments
Type Intent Optional Attributes Name
real(kind=r8) :: Control(0:UMFPACK_CONTROL-1)
Calls
Call graph
umf4zdef calls umfpack_defaults
umfpack_defaults calls umfpack_di_defaults, umfpack_zi_defaults
umfpack_di_defaults calls c_umfpack_di_defaults
umfpack_zi_defaults calls c_umfpack_zi_defaults