umf4cscal_ip – TOOLIB
umf4cscal_ip Subroutine
9 statements
Source File
public subroutine umf4cscal_ip(x, b, Numeric, status)
Arguments
Type Intent Optional Attributes Name
complex(kind=r8), intent(out) :: x(*)
complex(kind=r8), intent(in) :: b(*)
integer(kind=ip) :: Numeric
integer, intent(out) :: status
Calls
Called by
Call graph
umf4cscal_ip calls umfpack_scale_function
umfpack_scale_function calls umfpack_zi_scale, umfpack_ci_scale, umfpack_di_scale
umfpack_zi_scale calls umfpack_zi_scale, umfpack_ci_scale
umfpack_ci_scale calls c_umfpack_zi_scale
umfpack_di_scale calls c_umfpack_di_scale
umf4cscal calls umf4cscal_ip, umf4cscal
umf4scal calls umf4cscal_ip, umf4cscal, umf4scal, umf4zscal
umf4zscal calls umf4cscal_ip, umf4cscal, umf4zscal