umf4zfsym_ip – TOOLIB
umf4zfsym_ip Subroutine
7 statements
Source File
public subroutine umf4zfsym_ip(Symbolic)
Arguments
Type Intent Optional Attributes Name
integer(kind=ip) :: Symbolic
Calls
Called by
Call graph
umf4zfsym_ip calls umfpack_free_symbolic
umfpack_free_symbolic calls umfpack_di_free_symbolic, umfpack_zi_free_symbolic
umfpack_di_free_symbolic calls c_umfpack_di_free_symbolic
umfpack_zi_free_symbolic calls c_umfpack_zi_free_symbolic
umf4zfsym calls umf4zfsym_ip, umf4zfsym