umf4csol – TOOLIB
umf4csol Subroutine
11 statements
Source File
public subroutine umf4csol(sys, x, b, Numeric, Control, Info)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: sys
complex(kind=r8), intent(out) :: x(*)
complex(kind=r8), intent(in) :: b(*)
type(c_ptr) :: Numeric
real(kind=r8) :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8) :: Info(0:UMFPACK_INFO-1)
Calls
Call graph
umf4csol calls s_umfpack_solve
s_umfpack_solve calls s_umfpack_zi_solve, s_umfpack_ci_solve, s_umfpack_di_solve
s_umfpack_zi_solve calls s_umfpack_zi_solve, s_umfpack_ci_solve
s_umfpack_ci_solve calls umfpack_ci_solve
s_umfpack_di_solve calls umfpack_di_solve
umfpack_ci_solve calls c_umfpack_zi_solve
umfpack_di_solve calls c_umfpack_di_solve