umf4cssym_ip – TOOLIB
umf4cssym_ip Subroutine
10 statements
Source File
public subroutine umf4cssym_ip(Symbolic, filenum, status)
Arguments
Type Intent Optional Attributes Name
integer(kind=ip) :: Symbolic
integer, intent(in) :: filenum
integer, intent(out) :: status
Calls
Called by
Call graph
umf4cssym_ip calls umfpack_save_symbolic
umfpack_save_symbolic calls umfpack_di_save_symbolic, umfpack_zi_save_symbolic
umfpack_di_save_symbolic calls c_umfpack_di_save_symbolic
umfpack_zi_save_symbolic calls c_umfpack_zi_save_symbolic
umf4cssym calls umf4cssym_ip, umf4cssym