umf4lsym_ip – TOOLIB
umf4lsym_ip Subroutine
11 statements
Source File
public subroutine umf4lsym_ip(Symbolic, filenum, status)
Arguments
Type Intent Optional Attributes Name
integer(kind=ip) :: Symbolic
integer, intent(in) :: filenum
integer, intent(out) :: status
Calls
Called by
Call graph
umf4lsym_ip calls umfpack_load_symbolic
umfpack_load_symbolic calls umfpack_di_load_symbolic, umfpack_zi_load_symbolic
umfpack_di_load_symbolic calls c_umfpack_di_load_symbolic
umfpack_zi_load_symbolic calls c_umfpack_zi_load_symbolic
umf4lsym calls umf4lsym_ip, umf4lsym