umfpack_di_report_info – TOOLIB
umfpack_di_report_info Subroutine
17 statements
Source File
public subroutine umfpack_di_report_info(Control, Info)
Uses
iso_fortran_env
Arguments
Type Intent Optional Attributes Name
real(kind=r8), optional, target :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8), target :: Info(0:UMFPACK_INFO-1)
Calls
Called by
Call graph
umfpack_di_report_info calls c_umfpack_di_report_info
s_umfpack_di_report_info calls umfpack_di_report_info
close_solver calls umfpack_di_report_info
umfpack_report_info calls umfpack_di_report_info
s_umfpack_report_info calls umfpack_report_info
solve_syst calls close_solver, solution_solver
umf4cpinf calls umfpack_report_info
umf4pinf calls umfpack_report_info
umf4zpinf calls umfpack_report_info
solution_solver calls solve_syst
test_solvers calls solve_syst