umfpack_ci_numeric – TOOLIB
umfpack_ci_numeric Function
38 statements
Source File
public function umfpack_ci_numeric(Ap, Ai, Ax, Symbolic, Numeric, Control, Info)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), target :: Ap(*)
integer, intent(in), target :: Ai(*)
complex(kind=r8), intent(in), target :: Ax(*)
type(c_ptr), intent(in), optional :: Symbolic
type(c_ptr), optional :: Numeric
real(kind=r8), optional, target :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8), optional, target :: Info(0:UMFPACK_INFO-1)
Return Value integer
Calls
Called by
Call graph
umfpack_ci_numeric calls c_umfpack_zi_numeric
umfpack_numeric calls umfpack_ci_numeric, umfpack_zi_numeric
umfpack_zi_numeric calls umfpack_ci_numeric, umfpack_zi_numeric
s_umfpack_ci_numeric calls umfpack_ci_numeric
s_umfpack_numeric calls s_umfpack_ci_numeric, s_umfpack_zi_numeric
s_umfpack_zi_numeric calls s_umfpack_ci_numeric, s_umfpack_zi_numeric, umfpack_zi_numeric
umfpack_ci_operator_csc calls s_umfpack_ci_numeric
umfpack_ci_operator_csr calls s_umfpack_ci_numeric
umfpack_ci_operator_pcsc calls s_umfpack_ci_numeric
umfpack_ci_operator_pcsr calls s_umfpack_ci_numeric
operator(.umfpack.) calls umfpack_ci_operator_csc, umfpack_ci_operator_csr, umfpack_ci_operator_pcsc, umfpack_ci_operator_pcsr, umfpack_zi_operator_csc, umfpack_zi_operator_csr, umfpack_zi_operator_pcsc, umfpack_zi_operator_pcsr
umf4cnum calls s_umfpack_numeric, umf4cnum_ip, umf4cnum
umf4cnum_ip calls s_umfpack_numeric
umf4num calls s_umfpack_numeric, umf4cnum_ip, umf4num_ip, umf4znum_ip, umf4cnum, umf4num, umf4znum
umf4num_ip calls s_umfpack_numeric
umf4znum calls s_umfpack_numeric, umf4cnum_ip, umf4znum_ip, umf4cnum, umf4znum
umf4znum_ip calls s_umfpack_numeric
umfpack_zi_operator_csc calls s_umfpack_zi_numeric
umfpack_zi_operator_csr calls s_umfpack_zi_numeric
umfpack_zi_operator_pcsc calls s_umfpack_zi_numeric
umfpack_zi_operator_pcsr calls s_umfpack_zi_numeric