unit2IUc – TOOLIB
unit2IUc Function
9 statements
Source File
public function unit2IUc(string) result(met)
Convert a C type unit string into value (m)
Arguments
Type Intent Optional Attributes Name
character(kind=C_CHAR, len=1), intent(in), dimension(:) :: string
Return Value real(kind=R8)
Calls
Called by
Source Code
   function unit2IUc(string) result (met)
   !! Convert a C type unit string into value (m)
   implicit none
   real(kind=R8) :: met
   character(kind=C_CHAR), dimension(:), intent(in) :: string
      character(len=2) :: chaine
      chaine = string(1)//string(2)
      met    = unit2IUf(chaine)
   return
   endfunction unit2IUc
Call graph
unit2iuc calls unit2iuf
build_surf calls unit2iuc
trans_surf_tab calls unit2iuc
read_surf calls trans_surf_tab
write_surf calls build_surf
test_surfile calls read_surf, write_surf