urand – TOOLIB
urand Function
6 statements
Source File
private function urand(me) result(r)
Return the next pseudo-random deviate from a sequence which is uniformly distributed in the interval [0,1]
Type Bound
pikaia_class
Arguments
Type Intent Optional Attributes Name
class(pikaia_class), intent(inout) :: me
Return Value real(kind=wp)
Calls
Called by
Source Code
    function urand(me) result(r)
    implicit none
    class(pikaia_class),intent(inout) :: me
    real(wp) :: r
    r = me%rand%genrand64_real1()
    end function urand
Call graph
urand calls genrand64_real1
genrand64_real1 calls genrand64_int64
genrand64_int64 calls init_genrand64
cross calls urand
mutate calls urand
pikaia calls urand, cross, mutate, select_parents, stdrep
select_parents calls urand
stdrep calls urand
solve_with_pikaia calls pikaia
test_algen calls solve_with_pikaia