c_umfpack_di_scale – TOOLIB
c_umfpack_di_scale Interface
172 statements
Source File
interface
Called by
public function c_umfpack_di_scale(X, B, Numeric) bind(c,name='umfpack_di_scale')
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: X
type(c_ptr), intent(in), value :: B
type(c_ptr), intent(in), value :: Numeric
Return Value integer(kind=c_int)
Call graph
umfpack_di_scale calls c_umfpack_di_scale
umfpack_scale_function calls umfpack_di_scale
s_umfpack_di_scale calls umfpack_di_scale
s_umfpack_scale calls s_umfpack_di_scale
umf4cscal calls umfpack_scale_function, umf4cscal_ip, umf4cscal
umf4cscal_ip calls umfpack_scale_function
umf4scal calls umfpack_scale_function, umf4cscal_ip, umf4scal_ip, umf4zscal_ip, umf4cscal, umf4scal, umf4zscal
umf4scal_ip calls umfpack_scale_function
umf4zscal calls umfpack_scale_function, umf4cscal_ip, umf4zscal_ip, umf4cscal, umf4zscal
umf4zscal_ip calls umfpack_scale_function