c_umfpack_di_defaults – TOOLIB
c_umfpack_di_defaults Interface
172 statements
Source File
interface
Called by
public subroutine c_umfpack_di_defaults(Control) bind(c,name='umfpack_di_defaults')
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: Control
Call graph
umfpack_di_defaults calls c_umfpack_di_defaults
s_umfpack_di_defaults calls umfpack_di_defaults
init_solver calls umfpack_di_defaults
umfpack_defaults calls umfpack_di_defaults
s_umfpack_defaults calls umfpack_defaults
solve_syst calls init_solver, solution_solver
umf4cdef calls umfpack_defaults
umf4def calls umfpack_defaults
umf4zdef calls umfpack_defaults
solution_solver calls solve_syst
test_solvers calls solve_syst