c_umfpack_zi_scale – TOOLIB
c_umfpack_zi_scale Interface
172 statements
Source File
interface
Called by
public function c_umfpack_zi_scale(Xx, Xz, Bx, Bz, Numeric) bind(c,name='umfpack_zi_scale')
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: Xx
type(c_ptr), value :: Xz
type(c_ptr), intent(in), value :: Bx
type(c_ptr), intent(in), value :: Bz
type(c_ptr), intent(in), value :: Numeric
Return Value integer(kind=c_int)
Call graph
umfpack_ci_scale calls c_umfpack_zi_scale
umfpack_zi_scale calls c_umfpack_zi_scale, umfpack_ci_scale, umfpack_zi_scale
umfpack_scale_function calls umfpack_ci_scale, umfpack_zi_scale
s_umfpack_ci_scale calls umfpack_ci_scale
s_umfpack_scale calls s_umfpack_ci_scale, s_umfpack_zi_scale
s_umfpack_zi_scale calls s_umfpack_ci_scale, s_umfpack_zi_scale, umfpack_zi_scale
umf4cscal calls umfpack_scale_function, umf4cscal_ip, umf4cscal
umf4cscal_ip calls umfpack_scale_function
umf4scal calls umfpack_scale_function, umf4cscal_ip, umf4scal_ip, umf4zscal_ip, umf4cscal, umf4scal, umf4zscal
umf4scal_ip calls umfpack_scale_function
umf4zscal calls umfpack_scale_function, umf4cscal_ip, umf4zscal_ip, umf4cscal, umf4zscal
umf4zscal_ip calls umfpack_scale_function