c_umfpack_di_solve – TOOLIB
c_umfpack_di_solve Interface
172 statements
Source File
interface
Called by
public function c_umfpack_di_solve(sys, Ap, Ai, Ax, X, B, Numeric, Control, Info) bind(c,name='umfpack_di_solve')
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int), value :: sys
type(c_ptr), intent(in), value :: Ap
type(c_ptr), intent(in), value :: Ai
type(c_ptr), intent(in), value :: Ax
type(c_ptr), value :: X
type(c_ptr), intent(in), value :: B
type(c_ptr), intent(in), value :: Numeric
type(c_ptr), value :: Control
type(c_ptr), value :: Info
Return Value integer(kind=c_int)
Call graph
umfpack_di_solve calls c_umfpack_di_solve
umfpack_solve calls umfpack_di_solve
s_umfpack_di_solve calls umfpack_di_solve
s_umfpack_solve calls s_umfpack_di_solve
solution_solver calls s_umfpack_di_solve, solve_syst
umfpack_di_operator_csc calls s_umfpack_di_solve
umfpack_di_operator_csr calls s_umfpack_di_solve
umfpack_di_operator_pcsc calls s_umfpack_di_solve
umfpack_di_operator_pcsr calls s_umfpack_di_solve
operator(.umfpack.) calls umfpack_di_operator_csc, umfpack_di_operator_csr, umfpack_di_operator_pcsc, umfpack_di_operator_pcsr
solve_syst calls solution_solver
umf4csol calls s_umfpack_solve
umf4csolr calls s_umfpack_solve, umf4csolr_ip, umf4csolr
umf4csolr_ip calls s_umfpack_solve
umf4sol calls s_umfpack_solve, umf4sol_ip, umf4sol
umf4sol_ip calls s_umfpack_solve
umf4solr calls s_umfpack_solve, umf4csolr_ip, umf4solr_ip, umf4zsolr_ip, umf4csolr, umf4solr, umf4zsolr
umf4solr_ip calls s_umfpack_solve
umf4zsol calls s_umfpack_solve
umf4zsolr calls s_umfpack_solve, umf4csolr_ip, umf4zsolr_ip, umf4csolr, umf4zsolr
umf4zsolr_ip calls s_umfpack_solve
test_solvers calls solve_syst