c_umfpack_zi_solve – TOOLIB
c_umfpack_zi_solve Interface
172 statements
Source File
interface
Called by
public function c_umfpack_zi_solve(sys, Ap, Ai, Ax, Az, Xx, Xz, Bx, Bz, Numeric, Control, Info) bind(c,name='umfpack_zi_solve')
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int), value :: sys
type(c_ptr), intent(in), value :: Ap
type(c_ptr), intent(in), value :: Ai
type(c_ptr), intent(in), value :: Ax
type(c_ptr), intent(in), value :: Az
type(c_ptr), value :: Xx
type(c_ptr), value :: Xz
type(c_ptr), intent(in), value :: Bx
type(c_ptr), intent(in), value :: Bz
type(c_ptr), intent(in), value :: Numeric
type(c_ptr), value :: Control
type(c_ptr), value :: Info
Return Value integer(kind=c_int)
Call graph
umfpack_ci_solve calls c_umfpack_zi_solve
umfpack_zi_solve calls c_umfpack_zi_solve, umfpack_ci_solve, umfpack_zi_solve
umfpack_solve calls umfpack_ci_solve, umfpack_zi_solve
s_umfpack_ci_solve calls umfpack_ci_solve
s_umfpack_solve calls s_umfpack_ci_solve, s_umfpack_zi_solve
s_umfpack_zi_solve calls s_umfpack_ci_solve, s_umfpack_zi_solve, umfpack_zi_solve
umf4csol_ip calls s_umfpack_ci_solve
umfpack_ci_operator_csc calls s_umfpack_ci_solve
umfpack_ci_operator_csr calls s_umfpack_ci_solve
umfpack_ci_operator_pcsc calls s_umfpack_ci_solve
umfpack_ci_operator_pcsr calls s_umfpack_ci_solve
operator(.umfpack.) calls umfpack_ci_operator_csc, umfpack_ci_operator_csr, umfpack_ci_operator_pcsc, umfpack_ci_operator_pcsr, umfpack_zi_operator_csc, umfpack_zi_operator_csr, umfpack_zi_operator_pcsc, umfpack_zi_operator_pcsr
umf4csol calls umf4csol_ip, umf4csol, s_umfpack_solve
umf4sol calls umf4csol_ip, umf4csol, umf4sol, umf4zsol, umf4sol_ip, umf4zsol_ip, s_umfpack_solve
umf4zsol calls umf4csol_ip, umf4csol, umf4zsol, umf4zsol_ip, s_umfpack_solve
umf4csolr calls s_umfpack_solve, umf4csolr_ip, umf4csolr
umf4csolr_ip calls s_umfpack_solve
umf4sol_ip calls s_umfpack_solve
umf4solr calls s_umfpack_solve, umf4csolr_ip, umf4solr_ip, umf4zsolr_ip, umf4csolr, umf4solr, umf4zsolr
umf4solr_ip calls s_umfpack_solve
umf4zsol_ip calls s_umfpack_zi_solve
umf4zsolr calls s_umfpack_solve, umf4csolr_ip, umf4zsolr_ip, umf4csolr, umf4zsolr
umf4zsolr_ip calls s_umfpack_solve
umfpack_zi_operator_csc calls s_umfpack_zi_solve
umfpack_zi_operator_csr calls s_umfpack_zi_solve
umfpack_zi_operator_pcsc calls s_umfpack_zi_solve
umfpack_zi_operator_pcsr calls s_umfpack_zi_solve