c_umfpack_zi_numeric – TOOLIB
c_umfpack_zi_numeric Interface
172 statements
Source File
interface
Called by
public function c_umfpack_zi_numeric(Ap, Ai, Ax, Az, Symbolic, Numeric, Control, Info) bind(c,name='umfpack_zi_numeric')
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(in), value :: Ap
type(c_ptr), intent(in), value :: Ai
type(c_ptr), intent(in), value :: Ax
type(c_ptr), intent(in), value :: Az
type(c_ptr), intent(in), value :: Symbolic
type(c_ptr) :: Numeric
type(c_ptr), value :: Control
type(c_ptr), value :: Info
Return Value integer(kind=c_int)
Call graph
umfpack_ci_numeric calls c_umfpack_zi_numeric
umfpack_zi_numeric calls c_umfpack_zi_numeric, umfpack_ci_numeric, umfpack_zi_numeric
umfpack_numeric calls umfpack_ci_numeric, umfpack_zi_numeric
s_umfpack_ci_numeric calls umfpack_ci_numeric
s_umfpack_numeric calls s_umfpack_ci_numeric, s_umfpack_zi_numeric
s_umfpack_zi_numeric calls s_umfpack_ci_numeric, s_umfpack_zi_numeric, umfpack_zi_numeric
umfpack_ci_operator_csc calls s_umfpack_ci_numeric
umfpack_ci_operator_csr calls s_umfpack_ci_numeric
umfpack_ci_operator_pcsc calls s_umfpack_ci_numeric
umfpack_ci_operator_pcsr calls s_umfpack_ci_numeric
operator(.umfpack.) calls umfpack_ci_operator_csc, umfpack_ci_operator_csr, umfpack_ci_operator_pcsc, umfpack_ci_operator_pcsr, umfpack_zi_operator_csc, umfpack_zi_operator_csr, umfpack_zi_operator_pcsc, umfpack_zi_operator_pcsr
umf4cnum calls s_umfpack_numeric, umf4cnum_ip, umf4cnum
umf4cnum_ip calls s_umfpack_numeric
umf4num calls s_umfpack_numeric, umf4cnum_ip, umf4num_ip, umf4znum_ip, umf4cnum, umf4num, umf4znum
umf4num_ip calls s_umfpack_numeric
umf4znum calls s_umfpack_numeric, umf4cnum_ip, umf4znum_ip, umf4cnum, umf4znum
umf4znum_ip calls s_umfpack_numeric
umfpack_zi_operator_csc calls s_umfpack_zi_numeric
umfpack_zi_operator_csr calls s_umfpack_zi_numeric
umfpack_zi_operator_pcsc calls s_umfpack_zi_numeric
umfpack_zi_operator_pcsr calls s_umfpack_zi_numeric