c_umfpack_di_report_control – TOOLIB
c_umfpack_di_report_control Interface
172 statements
Source File
interface
Called by
public subroutine c_umfpack_di_report_control(Control) bind(c,name='umfpack_di_report_control')
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: Control
Call graph
umfpack_di_report_control calls c_umfpack_di_report_control
s_umfpack_di_report_control calls umfpack_di_report_control
init_solver calls umfpack_di_report_control
umfpack_report_control calls umfpack_di_report_control
s_umfpack_report_control calls umfpack_report_control
solve_syst calls init_solver, solution_solver
umf4cpcon calls umfpack_report_control
umf4pcon calls umfpack_report_control
umf4zpcon calls umfpack_report_control
solution_solver calls solve_syst
test_solvers calls solve_syst