c_umfpack_di_symbolic – TOOLIB
c_umfpack_di_symbolic Interface
172 statements
Source File
interface
Called by
public function c_umfpack_di_symbolic(n_row, n_col, Ap, Ai, Ax, Symbolic, Control, Info) bind(c,name='umfpack_di_symbolic')
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int), value :: n_row
integer(kind=c_int), value :: n_col
type(c_ptr), intent(in), value :: Ap
type(c_ptr), intent(in), value :: Ai
type(c_ptr), intent(in), value :: Ax
type(c_ptr) :: Symbolic
type(c_ptr), value :: Control
type(c_ptr), value :: Info
Return Value integer(kind=c_int)
Call graph
umfpack_di_symbolic calls c_umfpack_di_symbolic
umfpack_symbolic calls umfpack_di_symbolic
s_umfpack_di_symbolic calls umfpack_di_symbolic
s_umfpack_symbolic calls s_umfpack_di_symbolic
analyse_solver calls s_umfpack_di_symbolic
umfpack_di_operator_csc calls s_umfpack_di_symbolic
umfpack_di_operator_csr calls s_umfpack_di_symbolic
umfpack_di_operator_pcsc calls s_umfpack_di_symbolic
umfpack_di_operator_pcsr calls s_umfpack_di_symbolic
operator(.umfpack.) calls umfpack_di_operator_csc, umfpack_di_operator_csr, umfpack_di_operator_pcsc, umfpack_di_operator_pcsr
solve_syst calls analyse_solver, solution_solver
umf4csym calls s_umfpack_symbolic, umf4csym_ip, umf4csym
umf4csym_ip calls s_umfpack_symbolic
umf4sym calls s_umfpack_symbolic, umf4csym_ip, umf4sym_ip, umf4zsym_ip, umf4csym, umf4sym, umf4zsym
umf4sym_ip calls s_umfpack_symbolic
umf4zsym calls s_umfpack_symbolic, umf4csym_ip, umf4zsym_ip, umf4csym, umf4zsym
umf4zsym_ip calls s_umfpack_symbolic
solution_solver calls solve_syst
test_solvers calls solve_syst