c_umfpack_zi_symbolic – TOOLIB
c_umfpack_zi_symbolic Interface
172 statements
Source File
interface
Called by
public function c_umfpack_zi_symbolic(n_row, n_col, Ap, Ai, Ax, Az, Symbolic, Control, Info) bind(c,name='umfpack_zi_symbolic')
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int), value :: n_row
integer(kind=c_int), value :: n_col
type(c_ptr), intent(in), value :: Ap
type(c_ptr), intent(in), value :: Ai
type(c_ptr), intent(in), value :: Ax
type(c_ptr), intent(in), value :: Az
type(c_ptr) :: Symbolic
type(c_ptr), value :: Control
type(c_ptr), value :: Info
Return Value integer(kind=c_int)
Call graph
umfpack_ci_symbolic calls c_umfpack_zi_symbolic
umfpack_zi_symbolic calls c_umfpack_zi_symbolic, umfpack_ci_symbolic, umfpack_zi_symbolic
umfpack_symbolic calls umfpack_ci_symbolic, umfpack_zi_symbolic
s_umfpack_ci_symbolic calls umfpack_ci_symbolic
s_umfpack_symbolic calls s_umfpack_ci_symbolic, s_umfpack_zi_symbolic
s_umfpack_zi_symbolic calls s_umfpack_ci_symbolic, s_umfpack_zi_symbolic, umfpack_zi_symbolic
umfpack_ci_operator_csc calls s_umfpack_ci_symbolic
umfpack_ci_operator_csr calls s_umfpack_ci_symbolic
umfpack_ci_operator_pcsc calls s_umfpack_ci_symbolic
umfpack_ci_operator_pcsr calls s_umfpack_ci_symbolic
operator(.umfpack.) calls umfpack_ci_operator_csc, umfpack_ci_operator_csr, umfpack_ci_operator_pcsc, umfpack_ci_operator_pcsr, umfpack_zi_operator_csc, umfpack_zi_operator_csr, umfpack_zi_operator_pcsc, umfpack_zi_operator_pcsr
umf4csym calls s_umfpack_symbolic, umf4csym_ip, umf4csym
umf4csym_ip calls s_umfpack_symbolic
umf4sym calls s_umfpack_symbolic, umf4csym_ip, umf4sym_ip, umf4zsym_ip, umf4csym, umf4sym, umf4zsym
umf4sym_ip calls s_umfpack_symbolic
umf4zsym calls s_umfpack_symbolic, umf4csym_ip, umf4zsym_ip, umf4csym, umf4zsym
umf4zsym_ip calls s_umfpack_symbolic
umfpack_zi_operator_csc calls s_umfpack_zi_symbolic
umfpack_zi_operator_csr calls s_umfpack_zi_symbolic
umfpack_zi_operator_pcsc calls s_umfpack_zi_symbolic
umfpack_zi_operator_pcsr calls s_umfpack_zi_symbolic