c_umfpack_di_free_numeric – TOOLIB
c_umfpack_di_free_numeric Interface
172 statements
Source File
interface
Called by
public subroutine c_umfpack_di_free_numeric(Numeric) bind(c,name='umfpack_di_free_numeric')
Arguments
Type Intent Optional Attributes Name
type(c_ptr) :: Numeric
Call graph
umfpack_di_free_numeric calls c_umfpack_di_free_numeric
s_umfpack_di_free_numeric calls umfpack_di_free_numeric
close_solver calls umfpack_di_free_numeric
factorize_solver calls umfpack_di_free_numeric
freefact_solver calls umfpack_di_free_numeric
umfpack_di_operator_csc calls umfpack_di_free_numeric
umfpack_di_operator_csr calls umfpack_di_free_numeric
umfpack_di_operator_pcsc calls umfpack_di_free_numeric
umfpack_di_operator_pcsr calls umfpack_di_free_numeric
umfpack_free_numeric calls umfpack_di_free_numeric
operator(.umfpack.) calls umfpack_di_operator_csc, umfpack_di_operator_csr, umfpack_di_operator_pcsc, umfpack_di_operator_pcsr
s_umfpack_free_numeric calls umfpack_free_numeric
solve_syst calls close_solver, factorize_solver, freefact_solver, solution_solver
umf4cfnum calls umfpack_free_numeric, umf4cfnum_ip, umf4cfnum
umf4cfnum_ip calls umfpack_free_numeric
umf4fnum calls umfpack_free_numeric, umf4fnum_ip, umf4fnum
umf4fnum_ip calls umfpack_free_numeric
umf4zfnum calls umfpack_free_numeric, umf4zfnum_ip, umf4zfnum
umf4zfnum_ip calls umfpack_free_numeric
solution_solver calls solve_syst
test_solvers calls solve_syst