c_umfpack_di_numeric – TOOLIB
c_umfpack_di_numeric Interface
172 statements
Source File
interface
Called by
public function c_umfpack_di_numeric(Ap, Ai, Ax, Symbolic, Numeric, Control, Info) bind(c,name='umfpack_di_numeric')
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(in), value :: Ap
type(c_ptr), intent(in), value :: Ai
type(c_ptr), intent(in), value :: Ax
type(c_ptr), intent(in), value :: Symbolic
type(c_ptr) :: Numeric
type(c_ptr), value :: Control
type(c_ptr), value :: Info
Return Value integer(kind=c_int)
Call graph
umfpack_di_numeric calls c_umfpack_di_numeric
umfpack_numeric calls umfpack_di_numeric
s_umfpack_di_numeric calls umfpack_di_numeric
s_umfpack_numeric calls s_umfpack_di_numeric
factorize_solver calls s_umfpack_di_numeric
umfpack_di_operator_csc calls s_umfpack_di_numeric
umfpack_di_operator_csr calls s_umfpack_di_numeric
umfpack_di_operator_pcsc calls s_umfpack_di_numeric
umfpack_di_operator_pcsr calls s_umfpack_di_numeric
operator(.umfpack.) calls umfpack_di_operator_csc, umfpack_di_operator_csr, umfpack_di_operator_pcsc, umfpack_di_operator_pcsr
solve_syst calls factorize_solver, solution_solver
umf4cnum calls s_umfpack_numeric, umf4cnum_ip, umf4cnum
umf4cnum_ip calls s_umfpack_numeric
umf4num calls s_umfpack_numeric, umf4cnum_ip, umf4num_ip, umf4znum_ip, umf4cnum, umf4num, umf4znum
umf4num_ip calls s_umfpack_numeric
umf4znum calls s_umfpack_numeric, umf4cnum_ip, umf4znum_ip, umf4cnum, umf4znum
umf4znum_ip calls s_umfpack_numeric
solution_solver calls solve_syst
test_solvers calls solve_syst