c_umfpack_di_free_symbolic – TOOLIB
c_umfpack_di_free_symbolic Interface
172 statements
Source File
interface
Called by
public subroutine c_umfpack_di_free_symbolic(Symbolic) bind(c,name='umfpack_di_free_symbolic')
Arguments
Type Intent Optional Attributes Name
type(c_ptr) :: Symbolic
Call graph
umfpack_di_free_symbolic calls c_umfpack_di_free_symbolic
s_umfpack_di_free_symbolic calls umfpack_di_free_symbolic
close_solver calls umfpack_di_free_symbolic
umfpack_di_operator_csc calls umfpack_di_free_symbolic
umfpack_di_operator_csr calls umfpack_di_free_symbolic
umfpack_di_operator_pcsc calls umfpack_di_free_symbolic
umfpack_di_operator_pcsr calls umfpack_di_free_symbolic
umfpack_free_symbolic calls umfpack_di_free_symbolic
operator(.umfpack.) calls umfpack_di_operator_csc, umfpack_di_operator_csr, umfpack_di_operator_pcsc, umfpack_di_operator_pcsr
s_umfpack_free_symbolic calls umfpack_free_symbolic
solve_syst calls close_solver, solution_solver
umf4cfsym calls umfpack_free_symbolic, umf4cfsym_ip, umf4cfsym
umf4cfsym_ip calls umfpack_free_symbolic
umf4fsym calls umfpack_free_symbolic, umf4fsym_ip, umf4fsym
umf4fsym_ip calls umfpack_free_symbolic
umf4zfsym calls umfpack_free_symbolic, umf4zfsym_ip, umf4zfsym
umf4zfsym_ip calls umfpack_free_symbolic
solution_solver calls solve_syst
test_solvers calls solve_syst