dCreate_CompCol_Matrix – TOOLIB
dCreate_CompCol_Matrix Interface
98 statements
Source File
interface
Called by
private subroutine dCreate_CompCol_Matrix(A, m, n, nnz, nzval, rowind, colptr, stype, dtype, mtype) bind(c, name="dCreate_CompCol_Matrix")
Arguments
Type Intent Optional Attributes Name
type(SUPERMATRIX), intent(out) :: A
integer(kind=C_INT), intent(in), value :: m
integer(kind=C_INT), intent(in), value :: n
integer(kind=C_INT), intent(in), value :: nnz
real(kind=C_DOUBLE), intent(in) :: nzval(*)
integer(kind=C_INT), intent(in) :: rowind(*)
integer(kind=C_INT), intent(in) :: colptr(*)
integer(kind=C_INT), intent(in), value :: stype
integer(kind=C_INT), intent(in), value :: dtype
integer(kind=C_INT), intent(in), value :: mtype
Call graph
prep_superlu calls dcreate_compcol_matrix
analyse_solver calls prep_superlu
solv_superlu calls prep_superlu
solution_solver calls solv_superlu, solve_syst
solve_syst calls analyse_solver, solution_solver
test_solvers calls solve_syst