Destroy_CompCol_Matrix – TOOLIB
Destroy_CompCol_Matrix Interface
98 statements
Source File
interface
Called by
public subroutine Destroy_CompCol_Matrix(A) bind(c, name="Destroy_CompCol_Matrix")
Arguments
Type Intent Optional Attributes Name
type(SUPERMATRIX), intent(in) :: A
Call graph
close_superlu calls destroy_compcol_matrix
solv_superlu calls destroy_compcol_matrix
close_solver calls close_superlu
solution_solver calls solv_superlu, solve_syst
solve_syst calls close_solver, solution_solver
test_solvers calls solve_syst