Destroy_SuperNode_Matrix – TOOLIB
Destroy_SuperNode_Matrix Interface
98 statements
Source File
interface
Called by
public subroutine Destroy_SuperNode_Matrix(A) bind(c, name="Destroy_SuperNode_Matrix")
Arguments
Type Intent Optional Attributes Name
type(SUPERMATRIX), intent(in) :: A
Call graph
solv_superlu calls destroy_supernode_matrix
solution_solver calls solv_superlu, solve_syst
solve_syst calls solution_solver
test_solvers calls solve_syst