fftw_plan_dft_2d – TOOLIB
fftw_plan_dft_2d Interface
515 statements
Source File
interface
Called by
private function fftw_plan_dft_2d(n0, n1, in, out, sign, flags) bind(C, name='fftw_plan_dft_2d')
Arguments
Type Intent Optional Attributes Name
integer(kind=C_INT), value :: n0
integer(kind=C_INT), value :: n1
complex(kind=C_DOUBLE_COMPLEX), intent(out), dimension(*) :: in
complex(kind=C_DOUBLE_COMPLEX), intent(out), dimension(*) :: out
integer(kind=C_INT), value :: sign
integer(kind=C_INT), value :: flags
Return Value type(c_ptr)
Call graph
make_plan_fftw3 calls fftw_plan_dft_2d
tab_make_plan_fftw3 calls fftw_plan_dft_2d
init_fftw3 calls make_plan_fftw3
tab_init_fftw3 calls tab_make_plan_fftw3
calc_fftw3 calls init_fftw3
test_fftw3 calls init_fftw3, tab_init_fftw3, calc_fftw3