fftw_alloc_complex – TOOLIB
fftw_alloc_complex Interface
515 statements
Source File
interface
Called by
private function fftw_alloc_complex(n) bind(C, name='fftw_alloc_complex')
Arguments
Type Intent Optional Attributes Name
integer(kind=C_SIZE_T), value :: n
Return Value type(c_ptr)
Call graph
alloc_fftw3 calls fftw_alloc_complex
alloc_fftw3_real calls fftw_alloc_complex
tab_alloc_fftw3 calls fftw_alloc_complex
tab_alloc_fftw3_real calls fftw_alloc_complex
init_fftw3 calls alloc_fftw3
init_fftw3_real calls alloc_fftw3_real
tab_init_fftw3 calls tab_alloc_fftw3
tab_init_fftw3_real calls tab_alloc_fftw3_real
calc_fftw3 calls init_fftw3
calc_fftw3_real_bwd calls init_fftw3_real
calc_fftw3_real_fwd calls init_fftw3_real
test_fftw3 calls init_fftw3, init_fftw3_real, tab_init_fftw3, tab_init_fftw3_real, calc_fftw3, calc_fftw3_real_bwd, calc_fftw3_real_fwd