fftw_destroy_plan – TOOLIB
fftw_destroy_plan Interface
515 statements
Source File
interface
Called by
private subroutine fftw_destroy_plan(p) bind(C, name='fftw_destroy_plan')
Arguments
Type Intent Optional Attributes Name
type(C_PTR), value :: p
Call graph
destroy_plan_fftw3 calls fftw_destroy_plan
tab_destroy_plan_fftw3 calls fftw_destroy_plan
end_fftw3 calls destroy_plan_fftw3
tab_end_fftw3 calls tab_destroy_plan_fftw3
tab_end_fftw3_real calls tab_destroy_plan_fftw3
calc_fftw3 calls end_fftw3
calc_fftw3_real_bwd calls end_fftw3
calc_fftw3_real_fwd calls end_fftw3
test_fftw3 calls end_fftw3, tab_end_fftw3, tab_end_fftw3_real, calc_fftw3, calc_fftw3_real_bwd, calc_fftw3_real_fwd