fftw_execute_dft – TOOLIB
fftw_execute_dft Interface
515 statements
Source File
interface
Called by
private subroutine fftw_execute_dft(p, in, out) bind(C, name='fftw_execute_dft')
Arguments
Type Intent Optional Attributes Name
type(C_PTR), value :: p
complex(kind=C_DOUBLE_COMPLEX), intent(inout), dimension(*) :: in
complex(kind=C_DOUBLE_COMPLEX), intent(out), dimension(*) :: out
Call graph
calc_fftw3 calls fftw_execute_dft
tab_calc_fftw3 calls fftw_execute_dft
test_fftw3 calls calc_fftw3, tab_calc_fftw3