fftw_free – TOOLIB
fftw_free Interface
515 statements
Source File
interface
Called by
private subroutine fftw_free(p) bind(C, name='fftw_free')
Arguments
Type Intent Optional Attributes Name
type(C_PTR), value :: p
Call graph
desalloc_fftw3 calls fftw_free
tab_desalloc_fftw3 calls fftw_free
end_fftw3 calls desalloc_fftw3
tab_end_fftw3 calls tab_desalloc_fftw3
tab_end_fftw3_real calls tab_desalloc_fftw3
calc_fftw3 calls end_fftw3
calc_fftw3_real_bwd calls end_fftw3
calc_fftw3_real_fwd calls end_fftw3
test_fftw3 calls end_fftw3, tab_end_fftw3, tab_end_fftw3_real, calc_fftw3, calc_fftw3_real_bwd, calc_fftw3_real_fwd