s_umfpack_report_info – TOOLIB
s_umfpack_report_info Interface
3 statements
Source File
public interface s_umfpack_report_info
Calls
Module Procedures
public subroutine umfpack_report_info(Control, Info, version)
Arguments
Type Intent Optional Attributes Name
real(kind=r8), optional :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8) :: Info(0:UMFPACK_INFO-1)
character(len=*), optional :: version
Call graph
s_umfpack_report_info calls umfpack_report_info
umfpack_report_info calls umfpack_di_report_info, umfpack_zi_report_info
umfpack_di_report_info calls c_umfpack_di_report_info
umfpack_zi_report_info calls c_umfpack_zi_report_info