s_umfpack_report_control – TOOLIB
s_umfpack_report_control Interface
3 statements
Source File
public interface s_umfpack_report_control
Calls
Module Procedures
public subroutine umfpack_report_control(Control, version)
Arguments
Type Intent Optional Attributes Name
real(kind=r8), optional :: Control(0:UMFPACK_CONTROL-1)
character(len=*), optional :: version
Call graph
s_umfpack_report_control calls umfpack_report_control
umfpack_report_control calls umfpack_di_report_control, umfpack_zi_report_control
umfpack_di_report_control calls c_umfpack_di_report_control
umfpack_zi_report_control calls c_umfpack_zi_report_control