s_umfpack_defaults – TOOLIB
s_umfpack_defaults Interface
3 statements
Source File
public interface s_umfpack_defaults
Calls
Module Procedures
public subroutine umfpack_defaults(Control, version)
Arguments
Type Intent Optional Attributes Name
real(kind=r8), optional :: Control(0:UMFPACK_CONTROL-1)
character(len=*), optional :: version
Call graph
s_umfpack_defaults calls umfpack_defaults
umfpack_defaults calls umfpack_di_defaults, umfpack_zi_defaults
umfpack_di_defaults calls c_umfpack_di_defaults
umfpack_zi_defaults calls c_umfpack_zi_defaults