s_umfpack_zi_scale – TOOLIB
s_umfpack_zi_scale Interface
3 statements
Source File
public interface s_umfpack_zi_scale
Calls
Called by
Module Procedures
public interface s_umfpack_zi_scale()
Arguments
None
public subroutine s_umfpack_ci_scale(Xx, Bx, Numeric, status)
Arguments
Type Intent Optional Attributes Name
complex(kind=r8), intent(out) :: Xx(*)
complex(kind=r8), intent(in) :: Bx(*)
type(c_ptr), intent(in), optional :: Numeric
integer, optional :: status
Call graph
s_umfpack_zi_scale calls s_umfpack_zi_scale, s_umfpack_ci_scale
s_umfpack_ci_scale calls umfpack_ci_scale
umfpack_ci_scale calls c_umfpack_zi_scale
s_umfpack_scale calls s_umfpack_zi_scale