umf4zsnum – TOOLIB
umf4zsnum Interface
3 statements
Source File
public interface umf4zsnum
Calls
Module Procedures
public interface umf4zsnum()
Arguments
None
public subroutine umf4zsnum_ip(Numeric, filenum, status)
Arguments
Type Intent Optional Attributes Name
integer(kind=ip) :: Numeric
integer, intent(in) :: filenum
integer, intent(out) :: status
Call graph
umf4zsnum calls umf4zsnum, umf4zsnum_ip
umf4zsnum_ip calls umfpack_save_numeric
umfpack_save_numeric calls umfpack_di_save_numeric, umfpack_zi_save_numeric
umfpack_di_save_numeric calls c_umfpack_di_save_numeric
umfpack_zi_save_numeric calls c_umfpack_zi_save_numeric